# Generated by Django 3.2.3 on 2022-01-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220114_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='D',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='E',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='N',
            field=models.BigIntegerField(null=True),
        ),
    ]
