# Generated by Django 3.2.3 on 2022-01-02 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoapp', '0003_auto_20220103_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='share',
            field=models.ManyToManyField(blank=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
