# Generated by Django 3.2.3 on 2022-01-08 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_alter_photo_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='key',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
